#!/bin/bash

unset "${!NEKRS@}"
unset "${!OCCA@}"

export NEKRS_INSTALL_DIR=${HOME}/.local_yslan/nekrs_yslan
source ${NEKRS_INSTALL_DIR}/bin/nekrs.bashrc
bin=${NEKRS_INSTALL_DIR}/bin/nekrs

if [ $# -eq 0 ] || [ $# -ne 2 ] || [ "$1" == "-h" ] || [ "$1" == "-help" ]; then
  echo "usage: ${0##*/} <casename> <#procs>"
  exit 0
fi

rm -f logfile
mv $1.log.$2 $1.log1.$2 2>/dev/null
cmd="mpirun -np "$2" "$bin" --setup "$1
echo $cmd
echo $cmd > qq
echo $NEKRS_INSTALL_DIR >> qq
echo $bin >> qq
$cmd > $1.log.$2 &

ln -sf $1.log.$2 logfile
echo "started job in background"
echo "redirecting output to logfile"

